### ISSUE TITLE
Why this plugin?

### ISSUE THREAD

**Issue by markiewb** [diakogiannis/NB-Short-Maven-Project-Window#1]
Since NB7.4 you can configure it yourself

See https://benkiew.wordpress.com/2016/08/11/quicktip-how-to-customize-the-names-of-maven-project-nodes/

**Comment by diakogiannis** [comment]
I needed to create this plugin for two reasons. I was a given a project that had about 20 sub modules all with very long names. This made my life really difficult because if I wanted to do it the way you describe I needed lots of time and more importantly as it is a global configuration option I cannot choose what to see on the fly depenting on my project set. This also had to propagated to all my team. Also I had to do it to every installation that I had every time I need to work with this kind of projects. 
In this way I can do it in 1 second where ever I want.

I am closing this since it is not an issue.

Cheers
